#!/usr/bin/with-contenv bash
shopt -s globstar nullglob

# create folders
mkdir -p \
	/run/apache2 \
	/var/cache/smokeping

# copy config files
for file in /defaults/smoke-conf/*
 	do
		if [ ! -f "/config/${file}" ]
 		then
		cp "${file}" "/config/"
 	fi
 	done

# make symlinks
[[ ! -e /var/www/localhost/smokeping ]] && ln -s \
	/usr/share/webapps/smokeping /var/www/localhost/smokeping

[[ ! -e /var/www/localhost/smokeping/cache ]] && ln -s \
	/var/cache/smokeping /var/www/localhost/smokeping/cache

# permissions
chown -R abc:abc \
	/config \
	/data \
	/run/apache2 \
	/usr/share/webapps/smokeping \
	/var/cache/smokeping \
	/var/www/localhost/smokeping
