#!/usr/bin/with-contenv bash

# create folders
mkdir -p \
	/run/apache2 \
	/var/cache/smokeping

# copy config files
PREV_DIR=$(pwd)

cd /defaults/smoke-conf
	for i in `find . -type f`
 	do
		if [ ! -f "/config/${i}" ]
 		then
		cp "${i}" "/config/${i}"
 	fi
 	done
cd "${PREV_DIR}"

# make symlinks
[[ ! -e /var/www/localhost/smokeping ]] && ln -s \
	/usr/share/webapps/smokeping /var/www/localhost/smokeping

[[ ! -e /var/www/localhost/smokeping/cache ]] && ln -s \
	/var/cache/smokeping /var/www/localhost/smokeping/cache

# permissions
chown -R abc:abc \
	/config \
	/data \
	/run/apache2 \
	/usr/share/webapps/smokeping \
	/var/cache/smokeping \
	/var/www/localhost/smokeping
